using System.Collections.Generic;
using System.Text;

namespace Sinkii09.UIFramework.Editor
{
    /// <summary>
    /// Renders the machine-owned "{View}.Bindings.g.cs" partial. Pure: same inputs always produce a
    /// byte-identical string, which is what keeps regeneration out of the diff when nothing changed.
    /// Ordering is the caller's contract — the emitter never re-sorts.
    /// </summary>
    public static class BindingPartialEmitter
    {
        // '\n' is written explicitly everywhere. Environment.NewLine would make "regenerating an
        // unchanged prefab produces an identical file" false across machines.
        private const string NL = "\n";

        public static string Emit(string namespaceName, string className, string prefabGuid,
                                  IReadOnlyList<BindingCandidate> candidates)
        {
            var sb = new StringBuilder();

            // Silences IDE analyzers and StyleCop on generated code.
            sb.Append("// <auto-generated/>").Append(NL);
            sb.Append(BindingManifest.Format(prefabGuid, candidates).Replace("\n", NL));
            sb.Append("//").Append(NL);
            sb.Append("// Generated from the prefab by Tools/UIFramework/Create View + ViewModel.").Append(NL);
            sb.Append("// DO NOT EDIT - overwritten on the next generate. Bindings belong in ")
              .Append(className).Append(".cs.").Append(NL);
            sb.Append(NL);
            sb.Append("using UnityEngine;").Append(NL);
            sb.Append(NL);

            var hasNamespace = !string.IsNullOrWhiteSpace(namespaceName);
            var indent = hasNamespace ? "        " : "    ";

            if (hasNamespace)
            {
                sb.Append("namespace ").Append(namespaceName.Trim()).Append(NL);
                sb.Append("{").Append(NL);
            }

            // No base type here: the hand-written part declares it. Repeating it in a second part
            // is legal only while the two agree, and this file must never be the reason a rename
            // stops compiling.
            sb.Append(hasNamespace ? "    " : string.Empty)
              .Append("public partial class ").Append(className).Append(NL);
            sb.Append(hasNamespace ? "    " : string.Empty).Append("{").Append(NL);

            foreach (var c in candidates)
            {
                sb.Append(indent).Append("// ").Append(c.ChildPath).Append(NL);
                sb.Append(indent).Append("[SerializeField] private ").Append(c.TypeFullName)
                  .Append(' ').Append(c.FieldName).Append(';').Append(NL);
            }

            if (candidates.Count == 0)
                sb.Append(indent).Append("// No bindings selected.").Append(NL);

            sb.Append(hasNamespace ? "    " : string.Empty).Append("}").Append(NL);
            if (hasNamespace) sb.Append("}").Append(NL);

            return sb.ToString();
        }
    }
}
