using System.Linq;
using NUnit.Framework;
using Sinkii09.UIFramework.Editor;
using UnityEngine;

namespace Sinkii09.UIFramework.Tests.Editor
{
    // Phase 6 guards: everything that decides whether the generator is ALLOWED to write, plus the
    // hierarchy traversal. These are the branches that silently destroy or silently no-op, so each
    // one is pinned individually rather than through a single happy-path test.
    public class PrefabBindingGuardTests
    {
        private GameObject _root;

        [TearDown]
        public void TearDown()
        {
            if (_root != null) Object.DestroyImmediate(_root);
        }

        // --- Overwrite marker ----------------------------------------------------------------

        [Test]
        public void HasMarker_EmptyOrNullFile_IsNotOurs()
        {
            Assert.IsFalse(BindingManifest.HasMarker(null));
            Assert.IsFalse(BindingManifest.HasMarker(string.Empty));
        }

        [Test]
        public void HasMarker_HandWrittenFile_IsRefused()
        {
            Assert.IsFalse(BindingManifest.HasMarker("public partial class MyView { }"));
        }

        [Test]
        public void HasMarker_NearMissComment_IsRefused()
        {
            Assert.IsFalse(BindingManifest.HasMarker("// uifw-bindings-manifest\n"));
            Assert.IsFalse(BindingManifest.HasMarker("// uifw bindings manifest v1\n"));
        }

        [Test]
        public void HasMarker_NotOnFirstLine_IsStillOurs()
        {
            // The emitter puts <auto-generated/> above it, so line 1 is never the marker.
            Assert.IsTrue(BindingManifest.HasMarker("// <auto-generated/>\n" + BindingManifest.Marker + "\n"));
        }

        [Test]
        public void HasMarker_ByteOrderMarkAndCrLf_DoNotDecideOverwriteRights()
        {
            Assert.IsTrue(BindingManifest.HasMarker("\uFEFF" + BindingManifest.Marker + "\r\n"));
        }

        [Test]
        public void HasMarker_MarkerBuriedFarBelowTheHeader_IsRefused()
        {
            var body = new string('\n', 60) + BindingManifest.Marker;
            Assert.IsFalse(BindingManifest.HasMarker(body));
        }

        // --- Path validation -----------------------------------------------------------------

        [TestCase("MyView", "Assets/UI", ExpectedResult = true)]
        [TestCase("MyView", "Assets", ExpectedResult = true)]
        [TestCase("MyView", "Packages/com.x.y/Editor", ExpectedResult = true)]
        [TestCase("MyView", "Assets/../../etc", ExpectedResult = false)]
        [TestCase("MyView", "../outside", ExpectedResult = false)]
        [TestCase("MyView", "C:/Windows/System32", ExpectedResult = false)]
        [TestCase("MyView", "//server/share", ExpectedResult = false)]
        [TestCase("MyView", "AssetsEvil/UI", ExpectedResult = false)]
        [TestCase("MyView", "", ExpectedResult = false)]
        [TestCase("My View", "Assets/UI", ExpectedResult = false)]
        [TestCase("2View", "Assets/UI", ExpectedResult = false)]
        [TestCase("../Evil", "Assets/UI", ExpectedResult = false)]
        [TestCase("", "Assets/UI", ExpectedResult = false)]
        public bool ValidateTarget_RejectsEscapesAndIllegalNames(string viewName, string folder)
        {
            return PrefabBindingGenerator.ValidateTarget(viewName, folder) == null;
        }

        // --- Hand-file preconditions ---------------------------------------------------------

        [Test]
        public void DeclaresPartialClass_NonPartialView_IsRejected()
        {
            Assert.IsFalse(PrefabBindingGenerator.DeclaresPartialClass(
                "public class MyView : UIView<MyViewModel> { }", "MyView"));
        }

        [Test]
        public void DeclaresPartialClass_PartialView_IsAccepted()
        {
            Assert.IsTrue(PrefabBindingGenerator.DeclaresPartialClass(
                "public partial class MyView : UIView<MyViewModel> { }", "MyView"));
        }

        [Test]
        public void DeclaresPartialClass_DifferentClassInTheSameFile_DoesNotCount()
        {
            Assert.IsFalse(PrefabBindingGenerator.DeclaresPartialClass(
                "public partial class OtherView { }", "MyView"));
        }

        [Test]
        public void ExtractNamespace_TakesItFromTheHandFile_NotTheWizardField()
        {
            // A mismatched namespace makes the two parts different types, which compiles into a
            // baffling "no such member" rather than an obvious error.
            Assert.AreEqual("Game.UI.Screens",
                PrefabBindingGenerator.ExtractNamespace("using X;\nnamespace Game.UI.Screens\n{\n}"));
        }

        [Test]
        public void ExtractNamespace_GlobalNamespace_ReturnsEmpty()
        {
            Assert.AreEqual(string.Empty, PrefabBindingGenerator.ExtractNamespace("public partial class MyView { }"));
        }

        [Test]
        public void FindDeclaredFieldCollisions_FieldAlreadyHandWritten_IsReported()
        {
            var hand = "public partial class MyView { [SerializeField] private Image _healthBar; }";

            var collisions = PrefabBindingGenerator.FindDeclaredFieldCollisions(hand, new[] { "_healthBar", "_okButton" });

            CollectionAssert.AreEqual(new[] { "_healthBar" }, collisions);
        }

        // --- Scanner traversal ---------------------------------------------------------------

        [Test]
        public void Scan_ListsEveryComponentOnAChild_BecauseOneObjectCanNeedTwoFields()
        {
            _root = new GameObject("Root");
            var child = new GameObject("Health Bar");
            child.transform.SetParent(_root.transform);
            child.AddComponent<Animator>();
            child.AddComponent<CanvasGroup>();
            child.AddComponent<Canvas>();

            var results = PrefabBindingScanner.Scan(_root, new ScanOptions());

            Assert.AreEqual(3, results.Count);
            // Priority orders them; only the first is ticked by default.
            Assert.AreEqual("UnityEngine.CanvasGroup", results[0].Binding.TypeFullName);
            Assert.IsTrue(results[0].DefaultTicked);
            Assert.IsFalse(results[1].DefaultTicked);
            Assert.IsFalse(results[2].DefaultTicked);
        }

        [Test]
        public void Scan_SecondComponentOnAChild_IsTypeQualifiedNotParentQualified()
        {
            _root = new GameObject("Root");
            var child = new GameObject("Health Bar");
            child.transform.SetParent(_root.transform);
            child.AddComponent<CanvasGroup>();
            child.AddComponent<Canvas>();

            var results = PrefabBindingScanner.Scan(_root, new ScanOptions());

            Assert.AreEqual("_healthBar", results[0].Binding.FieldName);
            Assert.AreEqual("_healthBarCanvas", results[1].Binding.FieldName);
        }

        [Test]
        public void Scan_LayoutOnlyChild_ProducesNothingUntilShowAllIsTicked()
        {
            _root = new GameObject("Root");
            var child = new GameObject("Spacer");
            child.transform.SetParent(_root.transform);

            Assert.IsEmpty(PrefabBindingScanner.Scan(_root, new ScanOptions()));
            Assert.IsNotEmpty(PrefabBindingScanner.Scan(_root, new ScanOptions { ShowAllComponents = true }));
        }

        [Test]
        public void Scan_RootComponents_AreExcluded()
        {
            // The View MonoBehaviour itself lives on the root; binding the root to itself is noise.
            _root = new GameObject("Root");
            _root.AddComponent<CanvasGroup>();

            Assert.IsEmpty(PrefabBindingScanner.Scan(_root, new ScanOptions()));
        }

        [Test]
        public void Scan_NestedChildPath_IsRelativeToTheRoot()
        {
            _root = new GameObject("Root");
            var panel = new GameObject("Panel");
            panel.transform.SetParent(_root.transform);
            var label = new GameObject("Label");
            label.transform.SetParent(panel.transform);
            label.AddComponent<CanvasGroup>();

            var results = PrefabBindingScanner.Scan(_root, new ScanOptions());

            Assert.AreEqual("Panel/Label", results[0].Binding.ChildPath);
        }

        // --- Regression: CRITICAL 1 — collision scan must be declaration-shaped ---------------

        [Test]
        public void FindDeclaredFieldCollisions_FieldOnlyUsedNotDeclared_IsNotReported()
        {
            // The whole point of the feature is that {View}.cs USES the generated fields. Matching
            // a bare name made every run after the first refuse, blaming fields nobody wrote.
            var hand = @"public partial class MyView {
                             protected override void BindViewModel(MyViewModel vm) {
                                 _healthBar.fillAmount = 1f;
                                 _okButton.onClick.AddListener(vm.Ok);
                             }
                         }";

            var collisions = PrefabBindingGenerator.FindDeclaredFieldCollisions(
                hand, new[] { "_healthBar", "_okButton" });

            CollectionAssert.IsEmpty(collisions);
        }

        [TestCase("[SerializeField] private Image _healthBar;")]
        [TestCase("private Image _healthBar = null;")]
        [TestCase("protected readonly List<int> _healthBar;")]
        [TestCase("public Image[] _healthBar;")]
        public void FindDeclaredFieldCollisions_RealDeclarationShapes_AreStillReported(string declaration)
        {
            var hand = "public partial class MyView { " + declaration + " }";

            CollectionAssert.AreEqual(new[] { "_healthBar" },
                PrefabBindingGenerator.FindDeclaredFieldCollisions(hand, new[] { "_healthBar" }));
        }

        [Test]
        public void FindDeclaredFieldCollisions_NameOnlyInsideACommentOrString_IsNotReported()
        {
            var hand = "public partial class MyView { // private Image _healthBar;\n" +
                       "    void M() { var s = \"_okButton\"; } }";

            CollectionAssert.IsEmpty(PrefabBindingGenerator.FindDeclaredFieldCollisions(
                hand, new[] { "_healthBar", "_okButton" }));
        }

        // --- Regression: CRITICAL 2 — previously emitted names are pinned ---------------------

        [Test]
        public void Scan_ChildInsertedAheadOfAnExistingOne_DoesNotStealItsFieldName()
        {
            // Names used to be allocated first-come in traversal order, so inserting a child could
            // hand "_label" to a different GameObject. Unity serialises by field name, so the old
            // reference stays non-null and silently points at the wrong child.
            _root = new GameObject("Root");
            var existing = NewChild(_root, "ResumeButton");
            NewChild(existing, "Label");

            var firstRun = PrefabBindingScanner.Scan(_root, new ScanOptions())
                                               .Select(c => c.Binding).ToList();
            var labelBefore = firstRun.Single(b => b.ChildPath == "ResumeButton/Label").FieldName;

            var inserted = NewChild(_root, "AaaButton");
            inserted.transform.SetAsFirstSibling();
            NewChild(inserted, "Label");

            var secondRun = PrefabBindingScanner.Scan(_root, new ScanOptions(), firstRun);

            var labelAfter = secondRun.Single(c => c.Binding.ChildPath == "ResumeButton/Label")
                                      .Binding.FieldName;
            var newLabel = secondRun.Single(c => c.Binding.ChildPath == "AaaButton/Label")
                                    .Binding.FieldName;

            Assert.AreEqual(labelBefore, labelAfter, "an existing binding must keep its field name");
            Assert.AreNotEqual(labelBefore, newLabel, "the new child must not reuse a taken name");
        }

        [Test]
        public void Scan_WithoutAManifest_StillNamesEveryPairUniquely()
        {
            _root = new GameObject("Root");
            NewChild(NewChild(_root, "Header"), "Icon");
            NewChild(NewChild(_root, "Footer"), "Icon");

            var names = PrefabBindingScanner.Scan(_root, new ScanOptions())
                                            .Select(c => c.Binding.FieldName).ToList();

            CollectionAssert.AllItemsAreUnique(names);
        }

        [Test]
        public void Scan_SameNamedSiblings_DoNotShareOnePinnedFieldName()
        {
            // Sibling GameObjects may share a name, so two distinct pairs can produce the same
            // (childPath, type) key. Handing both the pinned name emits two identical fields and the
            // generated file does not compile. The pin may be claimed once; the rest fall through.
            _root = new GameObject("Root");
            var panel = NewChild(_root, "Panel");
            NewChild(panel, "Icon");
            NewChild(panel, "Icon");

            var previous = PrefabBindingScanner.Scan(_root, new ScanOptions())
                                               .Select(c => c.Binding).ToList();

            var names = PrefabBindingScanner.Scan(_root, new ScanOptions(), previous)
                                            .Select(c => c.Binding.FieldName).ToList();

            CollectionAssert.AllItemsAreUnique(names);
        }

        [Test]
        public void Scan_PinnedRun_KeepsEveryFieldNameUnique()
        {
            _root = new GameObject("Root");
            NewChild(NewChild(_root, "Header"), "Icon");
            NewChild(NewChild(_root, "Footer"), "Icon");

            var previous = PrefabBindingScanner.Scan(_root, new ScanOptions())
                                               .Select(c => c.Binding).ToList();

            // Insert more children so fresh allocation runs alongside the pinned names.
            NewChild(NewChild(_root, "Aside"), "Icon");

            var names = PrefabBindingScanner.Scan(_root, new ScanOptions(), previous)
                                            .Select(c => c.Binding.FieldName).ToList();

            CollectionAssert.AllItemsAreUnique(names);
        }

        [TestCase("return _healthBar = other;")]
        [TestCase("await _healthBar;")]
        [TestCase("throw _healthBar;")]
        public void FindDeclaredFieldCollisions_StatementKeywordBeforeTheName_IsNotADeclaration(string line)
        {
            var hand = "public partial class MyView { void M() { " + line + " } }";

            CollectionAssert.IsEmpty(
                PrefabBindingGenerator.FindDeclaredFieldCollisions(hand, new[] { "_healthBar" }));
        }

        private static GameObject NewChild(GameObject parent, string name)
        {
            var go = new GameObject(name, typeof(RectTransform), typeof(CanvasGroup));
            go.transform.SetParent(parent.transform, false);
            return go;
        }

        // --- Regression: WARNING 3 / S3 — text scans and name validation ----------------------

        [Test]
        public void ExtractNamespace_TwoNamespaceBlocks_TakesTheOneHoldingTheClass()
        {
            var hand = "namespace Game.Other\n{\n    class Helper { }\n}\n" +
                       "namespace Game.UI.Screens\n{\n    public partial class MyView { }\n}";

            Assert.AreEqual("Game.UI.Screens", PrefabBindingGenerator.ExtractNamespace(hand, "MyView"));
        }

        [Test]
        public void ExtractNamespace_NamespaceInsideABlockComment_IsIgnored()
        {
            var hand = "/* namespace Wrong.Ns { } */\nnamespace Game.UI\n{\n    public partial class MyView { }\n}";

            Assert.AreEqual("Game.UI", PrefabBindingGenerator.ExtractNamespace(hand, "MyView"));
        }

        [Test]
        public void DeclaresPartialClass_MentionedOnlyInAComment_IsRejected()
        {
            var hand = "// public partial class MyView { }\npublic class MyView { }";

            Assert.IsFalse(PrefabBindingGenerator.DeclaresPartialClass(hand, "MyView"));
        }

        [Test]
        public void ValidateTarget_CSharpKeyword_IsRejectedEvenThoughItIsALegalIdentifier()
        {
            Assert.IsNotNull(PrefabBindingGenerator.ValidateTarget("class", "Assets/Views"));
            Assert.IsNotNull(PrefabBindingGenerator.ValidateTarget("int", "Assets/Views"));
            Assert.IsNull(PrefabBindingGenerator.ValidateTarget("MyView", "Assets/Views"));
        }
    }
}
